// <auto-generated />
using System;
using CardManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable enable

namespace CardManagement.Infrastructure.Persistence.Migrations;

[DbContext(typeof(CardManagementDbContext))]
[Migration("20240101000000_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("CardManagement.Domain.Entities.Account", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid");

            b.Property<string>("AccountNumber")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.Property<string>("AccountType")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)");

            b.Property<long>("Balance")
                .HasColumnType("bigint");

            b.Property<DateTime>("CreatedAtUtc")
                .HasPrecision(3)
                .HasColumnType("timestamp(3) with time zone");

            b.Property<string>("Currency")
                .IsRequired()
                .HasMaxLength(3)
                .HasColumnType("character varying(3)");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)");

            b.Property<DateTime>("UpdatedAtUtc")
                .HasPrecision(3)
                .HasColumnType("timestamp(3) with time zone");

            b.HasKey("Id");

            b.HasIndex("AccountNumber")
                .IsUnique();

            b.ToTable("Accounts", (string)null!);
        });

        modelBuilder.Entity("CardManagement.Domain.Entities.Card", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid");

            b.Property<Guid>("AccountId")
                .HasColumnType("uuid");

            b.Property<string>("BinRange")
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnType("character varying(10)");

            b.Property<string>("CardScheme")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)");

            b.Property<DateTime>("CreatedAtUtc")
                .HasPrecision(3)
                .HasColumnType("timestamp(3) with time zone");

            b.Property<string>("Cvv2Encrypted")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)");

            b.Property<string>("ExpiryDate")
                .IsRequired()
                .HasMaxLength(5)
                .HasColumnType("character varying(5)");

            b.Property<string>("PanEncrypted")
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnType("character varying(512)");

            b.Property<string>("PanHash")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)");

            b.Property<DateTime>("UpdatedAtUtc")
                .HasPrecision(3)
                .HasColumnType("timestamp(3) with time zone");

            b.HasKey("Id");

            b.HasIndex("AccountId");

            b.HasIndex("PanHash")
                .IsUnique();

            b.ToTable("Cards", (string)null!);
        });

        modelBuilder.Entity("CardManagement.Domain.Entities.LedgerEntry", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid");

            b.Property<Guid>("AccountId")
                .HasColumnType("uuid");

            b.Property<long>("Amount")
                .HasColumnType("bigint");

            b.Property<DateTime>("CreatedAtUtc")
                .HasPrecision(3)
                .HasColumnType("timestamp(3) with time zone");

            b.Property<string>("Description")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<string>("EntryType")
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnType("character varying(10)");

            b.Property<string>("OperationIdentifier")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");

            b.Property<Guid>("TransactionId")
                .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("TransactionId");

            b.HasIndex("AccountId", "CreatedAtUtc");

            b.ToTable("LedgerEntries", (string)null!);
        });

        modelBuilder.Entity("CardManagement.Domain.Entities.ProcessorSession", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid");

            b.Property<string>("Endpoint")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)");

            b.Property<bool>("IsSignedOn")
                .HasColumnType("boolean");

            b.Property<DateTime?>("LastHeartbeatUtc")
                .HasPrecision(3)
                .HasColumnType("timestamp(3) with time zone");

            b.Property<DateTime?>("LastSignOnUtc")
                .HasPrecision(3)
                .HasColumnType("timestamp(3) with time zone");

            b.Property<string>("ProcessorType")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)");

            b.HasKey("Id");

            b.ToTable("ProcessorSessions", (string)null!);
        });

        modelBuilder.Entity("CardManagement.Domain.Entities.TransactionRecord", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid");

            b.Property<long>("Amount")
                .HasColumnType("bigint");

            b.Property<Guid>("CardId")
                .HasColumnType("uuid");

            b.Property<DateTime>("CreatedAtUtc")
                .HasPrecision(3)
                .HasColumnType("timestamp(3) with time zone");

            b.Property<string>("Currency")
                .IsRequired()
                .HasMaxLength(3)
                .HasColumnType("character varying(3)");

            b.Property<string>("MessageType")
                .IsRequired()
                .HasMaxLength(4)
                .HasColumnType("character varying(4)");

            b.Property<string>("PipelineStepReached")
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.Property<string>("ProcessorType")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)");

            b.Property<string>("ResponseCode")
                .HasMaxLength(2)
                .HasColumnType("character varying(2)");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)");

            b.Property<string>("SystemTraceAuditNumber")
                .IsRequired()
                .HasMaxLength(6)
                .HasColumnType("character varying(6)");

            b.HasKey("Id");

            b.HasIndex("CardId");

            b.HasIndex("SystemTraceAuditNumber")
                .IsUnique();

            b.ToTable("TransactionRecords", (string)null!);
        });

        modelBuilder.Entity("CardManagement.Domain.Entities.Card", b =>
        {
            b.HasOne("CardManagement.Domain.Entities.Account", null)
                .WithMany()
                .HasForeignKey("AccountId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });

        modelBuilder.Entity("CardManagement.Domain.Entities.LedgerEntry", b =>
        {
            b.HasOne("CardManagement.Domain.Entities.Account", null)
                .WithMany()
                .HasForeignKey("AccountId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });

        modelBuilder.Entity("CardManagement.Domain.Entities.TransactionRecord", b =>
        {
            b.HasOne("CardManagement.Domain.Entities.Card", null)
                .WithMany()
                .HasForeignKey("CardId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });
#pragma warning restore 612, 618
    }
}
