// <auto-generated />
using System;
using CardManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CardManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CardManagementDbContext))]
    [Migration("20260625100000_AddNotificationTables")]
    partial class AddNotificationTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CardManagement.Domain.PlatformServices.Notifications.DeliveryLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<DateTime>("DispatchedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Channel")
                        .HasDatabaseName("IX_NotificationDeliveryLogs_Channel");

                    b.HasIndex("DispatchedAtUtc")
                        .HasDatabaseName("IX_NotificationDeliveryLogs_DispatchedAtUtc");

                    b.HasIndex("RecipientId")
                        .HasDatabaseName("IX_NotificationDeliveryLogs_RecipientId");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("IX_NotificationDeliveryLogs_TemplateId");

                    b.ToTable("NotificationDeliveryLogs", (string)null);
                });

            modelBuilder.Entity("CardManagement.Domain.PlatformServices.Notifications.NotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryOptIn")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("FallbackChannel")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PrimaryChannel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId")
                        .IsUnique()
                        .HasDatabaseName("IX_NotificationPreferences_RecipientId");

                    b.ToTable("NotificationPreferences", (string)null);
                });

            modelBuilder.Entity("CardManagement.Domain.PlatformServices.Notifications.NotificationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EmailBodyTemplate")
                        .HasColumnType("text");

                    b.Property<string>("EmailSubjectTemplate")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string[]>("RequiredVariables")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SmsBodyTemplate")
                        .HasMaxLength(1600)
                        .HasColumnType("character varying(1600)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<string>("WhatsAppBodyTemplate")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_NotificationTemplates_Category");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_NotificationTemplates_Name");

                    b.ToTable("NotificationTemplates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
