namespace CardManagement.Infrastructure.Channels.Nibss;

/// <summary>
/// Internal abstraction over NIBSS mCash/USSD API calls for testability.
/// </summary>
public interface INibssMCashClient
{
    /// <summary>
    /// Submits a USSD payment instruction to NIBSS mCash.
    /// </summary>
    Task<MCashResponse> SubmitPaymentAsync(MCashRequest request, CancellationToken ct);

    /// <summary>
    /// Queries the status of a previously submitted mCash session.
    /// </summary>
    Task<MCashResponse> QueryStatusAsync(string sessionId, CancellationToken ct);
}

/// <summary>
/// Represents a payment request to NIBSS mCash/USSD.
/// </summary>
/// <param name="SessionId">Unique session identifier generated by the adapter.</param>
/// <param name="SourceAccount">Source account — typically a phone number or USSD short code.</param>
/// <param name="DestinationAccount">Destination account for the payment.</param>
/// <param name="Amount">Payment amount in minor currency units (kobo).</param>
/// <param name="PinBlock">Encrypted PIN block for PIN-based authentication (opaque to adapter).</param>
/// <param name="TransactionReference">Unique transaction reference for tracking.</param>
public record MCashRequest(
    string SessionId,
    string SourceAccount,
    string DestinationAccount,
    decimal Amount,
    string PinBlock,
    string TransactionReference);

/// <summary>
/// Represents a response from NIBSS mCash/USSD.
/// </summary>
public record MCashResponse(
    string ResponseCode,
    string? ResponseMessage,
    string? NibssReference);
