using CardManagement.Domain.ValueObjects;

namespace CardManagement.Domain.PlatformServices.Reconciliation;

/// <summary>
/// Represents a financial correction applied to resolve a reconciliation exception.
/// Can be created automatically by a rule engine or manually by an operator.
/// </summary>
public class Adjustment
{
    public Guid Id { get; private set; }
    public Guid ExceptionId { get; private set; }
    public AdjustmentType Type { get; private set; }
    public Money Amount { get; private set; } = null!;
    public string Reason { get; private set; } = string.Empty;
    public string? RuleName { get; private set; }
    public string OperatorId { get; private set; } = string.Empty;
    public DateTime CreatedAtUtc { get; private set; }

    private Adjustment() { }

    /// <summary>
    /// Creates an automatic adjustment generated by a rule engine.
    /// OperatorId is set to "system" for auto-adjustments.
    /// </summary>
    public static Adjustment CreateAutomatic(
        Guid exceptionId,
        Money amount,
        string reason,
        string ruleName)
    {
        if (exceptionId == Guid.Empty)
            throw new ArgumentException("Exception ID is required.", nameof(exceptionId));

        if (amount is null)
            throw new ArgumentNullException(nameof(amount));

        if (string.IsNullOrWhiteSpace(reason))
            throw new ArgumentException("Reason is required.", nameof(reason));

        if (string.IsNullOrWhiteSpace(ruleName))
            throw new ArgumentException("Rule name is required for automatic adjustments.", nameof(ruleName));

        return new Adjustment
        {
            Id = Guid.NewGuid(),
            ExceptionId = exceptionId,
            Type = AdjustmentType.AutoRule,
            Amount = amount,
            Reason = reason,
            RuleName = ruleName,
            OperatorId = "system",
            CreatedAtUtc = DateTime.UtcNow
        };
    }

    /// <summary>
    /// Creates a manual adjustment submitted by an operator.
    /// </summary>
    public static Adjustment CreateManual(
        Guid exceptionId,
        Money amount,
        string reason,
        string operatorId)
    {
        if (exceptionId == Guid.Empty)
            throw new ArgumentException("Exception ID is required.", nameof(exceptionId));

        if (amount is null)
            throw new ArgumentNullException(nameof(amount));

        if (string.IsNullOrWhiteSpace(reason))
            throw new ArgumentException("Reason is required.", nameof(reason));

        if (string.IsNullOrWhiteSpace(operatorId))
            throw new ArgumentException("Operator ID is required for manual adjustments.", nameof(operatorId));

        return new Adjustment
        {
            Id = Guid.NewGuid(),
            ExceptionId = exceptionId,
            Type = AdjustmentType.ManualOperator,
            Amount = amount,
            Reason = reason,
            RuleName = null,
            OperatorId = operatorId,
            CreatedAtUtc = DateTime.UtcNow
        };
    }
}
