apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cardmgmt

resources:
  - namespace.yaml
  - secrets.yaml
  - configmaps.yaml
  - pvcs.yaml
  - postgres.yaml
  - kafka.yaml
  - redis.yaml
  - waha.yaml
  - app.yaml
  - nginx.yaml
  - prometheus.yaml
  - grafana.yaml
  - grafana-dashboards-cm.yaml
