global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "card-management-api"
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ["card-management-app:8080"]
        labels:
          service: "card-management"
          environment: "development"
