using CardManagement.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CardManagement.Infrastructure.Persistence.Configurations;

/// <summary>
/// EF Core configuration for AuditEntry.
/// Uses sequential ID (identity column) for ordering, indexes on TransactionReference and CorrelationId
/// for efficient querying, and append-only semantics (no cascade deletes, no updates).
/// </summary>
public class AuditEntryConfiguration : IEntityTypeConfiguration<AuditEntry>
{
    public void Configure(EntityTypeBuilder<AuditEntry> builder)
    {
        builder.ToTable("AuditEntries");

        // Sequential ID generated by the database for ordering
        builder.HasKey(e => e.Id);
        builder.Property(e => e.Id)
            .UseIdentityAlwaysColumn();

        builder.Property(e => e.TransactionReference)
            .IsRequired()
            .HasMaxLength(128);

        builder.Property(e => e.TimestampUtc)
            .IsRequired()
            .HasPrecision(3);

        builder.Property(e => e.ActorIdentity)
            .IsRequired()
            .HasMaxLength(256);

        builder.Property(e => e.Action)
            .IsRequired()
            .HasMaxLength(128);

        builder.Property(e => e.PreviousState)
            .HasMaxLength(64);

        builder.Property(e => e.NewState)
            .HasMaxLength(64);

        builder.Property(e => e.CorrelationId)
            .IsRequired()
            .HasMaxLength(128);

        builder.Property(e => e.PreviousEntryHash)
            .HasMaxLength(64);

        builder.Property(e => e.EntryHash)
            .IsRequired()
            .HasMaxLength(64);

        // Index on TransactionReference for querying audit trail per transaction
        builder.HasIndex(e => e.TransactionReference)
            .HasDatabaseName("IX_AuditEntries_TransactionReference");

        // Index on CorrelationId for cross-transaction correlation queries
        builder.HasIndex(e => e.CorrelationId)
            .HasDatabaseName("IX_AuditEntries_CorrelationId");

        // No navigation properties, no foreign keys — append-only, no cascade deletes
    }
}
